"""
Generate `docs/TOOLS.md` from the authoritative tool definitions in `app/tools/`.

Usage:
  python tools/generate_tool_docs.py

This avoids documentation drift as MCP tools evolve.
"""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "app" / "tools"
OUT = ROOT / "docs" / "TOOLS.md"


def _is_mcp_tool_decorator(dec: ast.AST) -> bool:
    # mcp.tool()
    if (
        isinstance(dec, ast.Call)
        and isinstance(dec.func, ast.Attribute)
        and isinstance(dec.func.value, ast.Name)
        and dec.func.value.id == "mcp"
        and dec.func.attr == "tool"
    ):
        return True

    # @mcp.tool() without parentheses (less common in FastMCP but possible)
    if isinstance(dec, ast.Attribute) and isinstance(dec.value, ast.Name) and dec.value.id == "mcp" and dec.attr == "tool":
        return True

    return False


def _format_default(expr: ast.AST) -> str:
    try:
        v = ast.literal_eval(expr)
        if isinstance(v, str):
            return repr(v)
        return str(v)
    except Exception:
        return "…"


def _signature(fn: ast.FunctionDef) -> str:
    args = fn.args
    parts: list[str] = []

    for a in args.posonlyargs:
        parts.append(a.arg)
    if args.posonlyargs:
        parts.append("/")

    for a in args.args:
        parts.append(a.arg)

    if args.vararg:
        parts.append(f"*{args.vararg.arg}")

    for a in args.kwonlyargs:
        parts.append(a.arg)

    if args.kwarg:
        parts.append(f"**{args.kwarg.arg}")

    defaults = list(args.defaults)
    if defaults:
        for i in range(1, len(defaults) + 1):
            arg_name = args.args[-i].arg
            try:
                parts_index = parts.index(arg_name)
                parts[parts_index] = f"{arg_name}={_format_default(defaults[-i])}"
            except ValueError:
                pass

    for a, d in zip(args.kwonlyargs, args.kw_defaults):
        if d is None:
            continue
        name = a.arg
        try:
            idx = parts.index(name)
            parts[idx] = f"{name}={_format_default(d)}"
        except ValueError:
            pass

    return f"{fn.name}({', '.join(parts)})"


CATEGORY_ORDER: list[tuple[str, list[str]]] = [
    (
        "Forex & Stock Execution",
        [
            "place_market_order",
            "place_limit_order",
            "place_forex_order",
            "place_stock_order",
            "start_brokerage_private_ws",
            "deposit_paper_funds",
            "reset_paper_account",
        ],
    ),
    (
        "Market Intelligence",
        [
            "get_market_sentiment",
            "get_market_news",
            "get_economic_calendar",
            "get_forex_news",
            "get_forex_market_brief",
            "get_social_sentiment",
            "get_financial_news",
            "get_free_news",
        ],
    ),
    (
        "Analytics & Research",
        [
            "get_stock_price",
            "get_multiple_prices",
            "get_market_regime",
            "fetch_ohlcv",
            "run_backtest_simulation",
            "post_market_insight",
            "get_latest_insights",
        ],
    ),
]


def find_tools_in_tree(tree: ast.AST) -> dict[str, ast.FunctionDef]:
    tools = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            if any(_is_mcp_tool_decorator(d) for d in node.decorator_list):
                tools[node.name] = node
    return tools


def main() -> int:
    all_tools: dict[str, ast.FunctionDef] = {}

    # Scan app/tools/*.py
    for py_file in TOOLS_DIR.glob("*.py"):
        if py_file.name == "__init__.py":
            continue
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
        all_tools.update(find_tools_in_tree(tree))

    used: set[str] = set()
    lines: list[str] = []

    lines.append("# ReadyTrader-FOREX MCP Tool Catalog")
    lines.append("")
    lines.append("This file is automatically generated from the tool definitions in `app/tools/`.")
    lines.append("")
    lines.append("> [!TIP]")
    lines.append("> AI agents can use these tools to gather intelligence, assess risk, and execute trades.")
    lines.append("")

    for section, names in CATEGORY_ORDER:
        present = [n for n in names if n in all_tools]
        if not present:
            continue
        used.update(present)
        lines.append(f"## {section}")
        lines.append("")
        lines.append("| Tool Name | Description |")
        lines.append("| :--- | :--- |")

        for name in present:
            fn = all_tools[name]
            doc = (ast.get_docstring(fn) or "").strip()
            first = doc.splitlines()[0].strip() if doc else "No description."
            lines.append(f"| [`{fn.name}`](#{fn.name.replace('_', '-')}) | {first} |")
        lines.append("")

        for name in present:
            fn = all_tools[name]
            sig = _signature(fn)
            doc = (ast.get_docstring(fn) or "").strip()
            lines.append(f"### `{fn.name}`")
            lines.append("")
            lines.append(f"**Signature:** `{sig}`")
            lines.append("")
            if doc:
                lines.append(f"```text\n{doc}\n```")
            lines.append("")
            lines.append("---")
            lines.append("")

    leftovers = sorted(set(all_tools) - used)
    if leftovers:
        lines.append("## Uncategorized")
        lines.append("")
        lines.append("| Tool Name | Description |")
        lines.append("| :--- | :--- |")
        for name in leftovers:
            fn = all_tools[name]
            doc = (ast.get_docstring(fn) or "").strip()
            first = doc.splitlines()[0].strip() if doc else "No description."
            lines.append(f"| [`{fn.name}`](#{fn.name.replace('_', '-')}) | {first} |")
        lines.append("")

        for name in leftovers:
            fn = all_tools[name]
            sig = _signature(fn)
            doc = (ast.get_docstring(fn) or "").strip()
            lines.append(f"### `{fn.name}`")
            lines.append("")
            lines.append(f"**Signature:** `{sig}`")
            lines.append("")
            if doc:
                lines.append(f"```text\n{doc}\n```")
            lines.append("")
            lines.append("---")
            lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(all_tools)} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
