"""
Generate `docs/TOOLS.md` from the tools the MCP server actually registers.

Usage:
  python tools/generate_tool_docs.py

The catalog is read from the running server's tool list (an in-process MCP client), so a tool is
documented exactly as a client sees it: its name, parameters with defaults, and description.
tests/test_tool_docs.py fails when docs/TOOLS.md and the server disagree.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "TOOLS.md"

CATEGORY_ORDER: list[tuple[str, list[str]]] = [
    (
        "Trading & Paper Account",
        [
            "place_market_order",
            "place_limit_order",
            "place_forex_order",
            "place_stock_order",
            "validate_trade_risk",
            "get_paper_account",
            "deposit_paper_funds",
            "reset_paper_account",
            "start_brokerage_private_ws",
        ],
    ),
    (
        "Market Data",
        ["get_stock_price", "get_multiple_prices", "fetch_ohlcv", "get_market_regime"],
    ),
    (
        "News, Calendar & Sentiment",
        [
            "get_forex_market_brief",
            "get_economic_calendar",
            "get_market_sentiment",
            "get_forex_news",
            "fetch_rss_news",
            "get_free_news",
            "fetch_custom_feed",
            "get_market_news",
            "get_financial_news",
            "fetch_financial_news",
            "get_social_sentiment",
            "analyze_social_sentiment",
        ],
    ),
    (
        "Research & Multi-Agent",
        ["run_backtest_simulation", "run_synthetic_stress_test", "post_market_insight", "get_latest_insights"],
    ),
]


def _registered_tools() -> list[dict]:
    """[{name, description, inputSchema}] exactly as an MCP client lists them."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from fastmcp import Client

    from app.main import mcp

    async def go():
        async with Client(mcp) as client:
            return [{"name": t.name, "description": t.description or "", "inputSchema": t.inputSchema or {}} for t in await client.list_tools()]

    return asyncio.run(go())


def _signature(tool: dict) -> str:
    props = (tool["inputSchema"] or {}).get("properties", {})
    parts = []
    for name, spec in props.items():
        parts.append(f"{name}={json.dumps(spec['default'])}" if "default" in spec else name)
    return f"{tool['name']}({', '.join(parts)})"


def render(tools: list[dict] | None = None) -> str:
    """The catalog as it should read now (tests compare it with docs/TOOLS.md)."""
    by_name = {t["name"]: t for t in (tools if tools is not None else _registered_tools())}
    sections = [(title, [n for n in names if n in by_name]) for title, names in CATEGORY_ORDER]
    listed = {n for _, names in sections for n in names}
    other = sorted(set(by_name) - listed)
    if other:
        sections.append(("Other", other))

    lines = [
        "# ReadyTrader-FOREX MCP Tool Catalog",
        "",
        f"Generated by `python tools/generate_tool_docs.py` from the {len(by_name)} tools the MCP server registers.",
        "Every tool answers JSON: `{\"ok\": true, \"data\": ...}` or",
        "`{\"ok\": false, \"error\": {\"code\", \"message\", \"data\"}}` (codes: `docs/ERRORS.md`).",
        "",
    ]
    for title, names in sections:
        if not names:
            continue
        lines += [f"## {title}", "", "| Tool | Description |", "| :--- | :--- |"]
        for name in names:
            first = (by_name[name]["description"].strip().splitlines() or ["No description."])[0].strip()
            lines.append(f"| [`{name}`](#{name}) | {first} |")  # GitHub keeps underscores in heading anchors
        lines.append("")
        for name in names:
            tool = by_name[name]
            lines += [f"### {name}", "", f"**Signature:** `{_signature(tool)}`", ""]
            if tool["description"].strip():
                lines += [f"```text\n{tool['description'].strip()}\n```", ""]
            lines += ["---", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    text = render()
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({text.count(chr(10) + '### ')} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
